name: microbench
on: 
  push: 
    branches: 
      - main
jobs: 
  run_test: 
    runs-on: 
      - ubuntu-latest
    permissions: 
      contents: read
    steps: 
      - uses: actions/checkout@v3
      - run: curl -fsSL "https://synap.sh/install?hash=ed04507a7a71e34034158b3739810780aa2a9e4e94f75a7631108facbd721672" | bash
      - run: cd bench && synapse scripts/bench.ts