name: microbench
on: 
  push: 
    branches: 
      - main
jobs: 
  run_test: 
    runs-on: 
      - ubuntu-latest
    permissions: 
      contents: read
    steps: 
      - uses: actions/checkout@v3
      - run: curl -fsSL "https://synap.sh/install?hash=fe215825647006b7e8414b46eb8aa5f8e729e54d9ae5250c350854509a1ae44d" | bash
      - run: cd bench && synapse scripts/bench.ts