name: microbench
on: 
  push: 
    branches: 
      - main
jobs: 
  run_test: 
    runs-on: 
      - ubuntu-latest
    permissions: 
      contents: read
    steps: 
      - uses: actions/checkout@v3
      - run: curl -fsSL "https://synap.sh/install?hash=48f4ce0ae83d1b8b1f7bee0d3fba881abf744fb12fbae4f37a29d0beebff150b" | bash
      - run: cd bench && synapse scripts/bench.ts